=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Auftrag.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Auftrag.schema.json",
  "title": "Auftrag",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "AUFTRAG"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "ausfuehrungsdatum": {
      "type": "string",
      "format": "date-time",
      "description": "ausfuehrungsdatum"
    },
    "fertigstellungsdatum": {
      "type": "string",
      "format": "date-time",
      "description": "fertigstellungsdatum"
    },
    "startdatum": {
      "type": "string",
      "format": "date-time",
      "description": "startdatum"
    },
    "sparte": {
      "$ref": "../enum/Sparte.schema.json"
    },
    "lieferanschrift": {
      "$ref": "../com/Adresse.schema.json"
    },
    "marktlokationsId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      },
      "description": "marktlokationsId"
    },
    "mindestpreis": {
      "$ref": "../com/Preis.schema.json"
    },
    "hoechstpreis": {
      "$ref": "../com/Preis.schema.json"
    },
    "energierichtung": {
      "$ref": "../enum/Energierichtung.schema.json"
    },
    "berechnungspreis": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.25,
          "min": 1,
          "max": 10
        }
      },
      "description": "berechnungspreis"
    },
    "summeGesamt": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.25,
          "min": 10,
          "max": 20
        }
      },
      "description": "summeGesamt"
    },
    "verschobenerAbmeldetermin": {
      "type": "string",
      "format": "date-time",
      "description": "verschobenerAbmeldetermin"
    },
    "behebungsZeitpunkt": {
      "type": "string",
      "format": "date-time",
      "description": "behebungsZeitpunkt"
    },
    "lieferadresseAltgeraete": {
      "$ref": "../bo/Geschaeftspartner.schema.json"
    },
    "definitionsTyp": {
      "$ref": "../enum/DefinitionsTyp.schema.json"
    },
    "positionsdaten": {
      "type": "array",
      "items": {
        "$ref": "../com/AuftragPosition.schema.json"
      },
      "description": "positionsdaten"
    },
    "bemerkungen": {
      "type": "array",
      "items": {
        "type": "string",
        "faker": {
          "lorem.sentence": 5
        }
      },
      "description": "bemerkungen"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/Auftrag.json
{
  "boTyp": "AUFTRAG",
  "versionStruktur": "1",
  "ausfuehrungsdatum": "1902-01-14T18:11:20.0Z",
  "fertigstellungsdatum": "1912-02-21T10:44:24.0Z",
  "startdatum": "1920-05-17T15:37:52.0Z",
  "sparte": "STROM",
  "lieferanschrift": {
    "postleitzahl": "83940",
    "ort": "Steffenburg",
    "strasse": "Rat-Deycks-Str.",
    "hausnummer": "6",
    "postfach": "enim",
    "adresszusatz": "sint laboris Lorem in",
    "coErgaenzung": "magna reprehenderit irure",
    "landescode": "NG",
    "ortsteil": "West Maik",
    "zusatzInformation": {
      "zusatz1": "ut non exercitation reprehenderit et",
      "zusatz2": "nisi exercitation reprehenderit velit",
      "zusatz3": "magna",
      "zusatz4": "voluptate commodo nisi labore ex",
      "zusatz5": "qui dolor ea et"
    }
  },
  "marktlokationsId": "18784845894",
  "mindestpreis": {
    "wert": 7.5,
    "einheit": "CT",
    "bezugswert": "WH",
    "status": "VORLAEUFIG"
  },
  "hoechstpreis": {
    "wert": 9.75,
    "einheit": "CT",
    "bezugswert": "PROZENT",
    "status": "ENDGUELTIG"
  },
  "energierichtung": "EINSP",
  "berechnungspreis": 5,
  "summeGesamt": 13.75,
  "verschobenerAbmeldetermin": "1958-11-11T19:01:20.0Z",
  "behebungsZeitpunkt": "1965-08-12T18:33:19.0Z",
  "lieferadresseAltgeraete": {
    "boTyp": "GESCHAEFTSPARTNER",
    "versionStruktur": 1,
    "anrede": "Prof. Dr.",
    "name1": "Gr√ºn",
    "name2": "Viktor",
    "name3": "nulla aliqua in",
    "name4": "aute adipisicing nulla",
    "umsatzsteuerId": "DE111101101",
    "glaeubigerId": "791652",
    "emailAdresse": "Mikail.Dold98@yahoo.com",
    "website": "https://uberraschend-monarchie.net",
    "gewerbekennzeichnung": true,
    "hrnummer": "282035",
    "amtsgericht": "Edgarscheid",
    "partneradresse": {
      "postleitzahl": "46825",
      "ort": "Nicolasstadt",
      "strasse": "Bergische Landstr.",
      "hausnummer": "41a",
      "postfach": "culpa dolor ipsum reprehenderit fugiat",
      "adresszusatz": "ut quis nulla ut dolore",
      "coErgaenzung": "sint",
      "landescode": "BJ",
      "ortsteil": "Enricodorf",
      "zusatzInformation": {
        "zusatz1": "in tempor nisi voluptate",
        "zusatz2": "deserunt",
        "zusatz3": "non",
        "zusatz4": "voluptate veniam ut reprehenderit",
        "zusatz5": "nisi"
      }
    },
    "externeKundenummerLieferant": "152079",
    "externeReferenzen": [
      {
        "exRefName": "Kundennummer beim Altlieferanten",
        "exRefWert": "3062916972"
      }
    ],
    "geschaeftspartnerrolle": [
      "INTERESSENT"
    ],
    "kontaktweg": [
      "ANSCHREIBEN"
    ]
  },
  "definitionsTyp": "LEISTUNGSKURVEN",
  "positionsdaten": [
    {
      "positionsnummer": 40673023,
      "positionsnummerAngebot": "705052",
      "energieerfassung": "SEPARAT_ERFASSEN",
      "artikelnummer": "REGELENERGIE_LEISTUNG",
      "positionsbetrag": "78",
      "startdatum": "1954-10-26T16:48:06.0Z",
      "enddatum": "1954-08-28T15:01:22.0Z",
      "istBestand": "5",
      "obiskennzahl": "cillum aliqua",
      "anfragegrund": "DIREKTER_VERTRAG_MSB_ANN",
      "allgemeineInformationen": {
        "info1": "adipisicing nostrud",
        "info2": "anim",
        "info3": "deserunt occaecat",
        "info4": "ut nostrud aliqua pariatur eu",
        "info5": "cupidatat"
      },
      "infoAbweichung": {
        "abweichung1": "irure ea nulla",
        "abweichung2": "laboris est eu",
        "abweichung3": "quis fugiat",
        "abweichung4": "deserunt fugiat occaecat in non",
        "abweichung5": "anim nostrud"
      },
      "definitionsTyp": "SCHALTZEIT"
    }
  ],
  "bemerkungen": [
    "Sequi ipsum sequi voluptates repudiandae."
  ]
}
