=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Berechnungsformel.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Berechnungsformel.schema.json",
  "title": "Berechnungsformel",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "BERECHNUNGSFORMEL"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "beginndatum": {
      "type": "string",
      "format": "date-time",
      "description": "Der inklusive Zeitpunkt ab dem die Berechnungsformel gültig ist"
    },
    "notwendigkeit": {
      "$ref": "../enum/BerechnungsformelNotwendigkeit.schema.json",
      "description": "Beschreibt ob eine Berechnungsformel notwendig ist"
    },
    "lieferrichtung": {
      "$ref": "../enum/Energierichtung.schema.json",
      "description": "The UTILTS 'Lieferrichtung der Marktlokation' is contained in the marktlokations-bo also the relation between Berechnungsformel↔ Marktlokation is modelled as 'link'"
    },
    "rechenschrittId": {
      "type": "integer",
      "faker": {
        "number.int": {
          "min": 1,
          "max": 10
        }
      },
      "description": "ID des Rechenschritts [1 - 99999]"
    },
    "rechenschritt": {
      "$ref": "../com/Rechenschritt.schema.json"
    },
    "rechenschritte": {
      "type": "array",
      "items": {
        "$ref": "../com/Rechenschritt.schema.json"
      },
      "description": "Eine Berechnungsformel enthält, falls sie notwendig ist, einen oder mehrere Berechnungschritte, die hier rekursiv abgebildet werden."
    },
    "verwendungszweck": {
      "type": "array",
      "items": {
        "$ref": "../com/Verwendungszweck.schema.json"
      },
      "description": "Verwendungszweck der Werte"
    },
    "gueltigkeitszeitraum": {
      "$ref": "../com/Zeitraum.schema.json",
      "description": "Gültigkeitszeitraum der Werte"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Berechnungsformel.json
{
  "boTyp": "BERECHNUNGSFORMEL",
  "versionStruktur": "1",
  "beginndatum": "1964-12-05T16:58:01.0Z",
  "notwendigkeit": "BERECHNUNGSFORMEL_MUSS_ANGEFRAGT_WERDEN",
  "lieferrichtung": "EINSP",
  "rechenschrittId": 9,
  "rechenschritt": {
    "rechenschrittBestandteilId": 3,
    "referenzRechenschrittId": 1,
    "operation": "SUBTRAKTION",
    "verlustfaktorTrafo": 5.25,
    "verlustfaktorLeitung": 7,
    "aufteilungsfaktorEnergiemenge": 2.25,
    "messlokationsId": "235976085992504755955526967048073",
    "energieflussrichtung": "EINSP"
  },
  "rechenschritte": [
    {
      "rechenschrittBestandteilId": 5,
      "referenzRechenschrittId": 9,
      "operation": "SUBTRAKTION",
      "verlustfaktorTrafo": 6.25,
      "verlustfaktorLeitung": 7.5,
      "aufteilungsfaktorEnergiemenge": 2.25,
      "messlokationsId": "920906799706572143967310975155223",
      "energieflussrichtung": "AUSSP"
    }
  ],
  "verwendungszweck": [
    {
      "marktrolle": "INTERESSENT",
      "zweck": [
        "BLINDARBEITSABRECHNUNG"
      ]
    }
  ],
  "gueltigkeitszeitraum": {
    "zeiteinheit": "STUNDE",
    "dauer": 5,
    "startdatum": "1959-12-30T05:39:47.0Z",
    "enddatum": "1953-04-18T04:48:46.0Z",
    "einheit": "MONAT",
    "ableseZeitraum": "689002",
    "abrechnungsZeitraum": "542657",
    "zeitraumText": "ut ullamco",
    "zeitraumId": 9
  }
}
