=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Geschaeftspartner.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Geschaeftspartner.schema.json",
  "title": "Geschaeftspartner",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "GESCHAEFTSPARTNER"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "anrede": {
      "type": "string",
      "faker": "person.prefix",
      "description": "Die Anrede für den GePa, Z.B. Herr."
    },
    "name1": {
      "type": "string",
      "faker": "person.lastName",
      "description": "Erster Teil des Namens. Hier kann der Firmenname oder bei Privatpersonen\nbeispielsweise der Nachname dargestellt werden. Beispiele: Yellow Strom GmbH\noder Hagen"
    },
    "name2": {
      "type": "string",
      "faker": "person.firstName",
      "description": "Zweiter Teil des Namens. Hier kann der eine Erweiterung zum Firmennamen oder\nbei Privatpersonen beispielsweise der Vorname dargestellt werden. Beispiele:\nBereich Süd oder Nina"
    },
    "name3": {
      "type": "string",
      "description": "Dritter Teil des Namens. Hier können weitere Ergänzungen zum Firmennamen oder\nbei Privatpersonen Zusätze zum Namen dargestellt werden. Beispiele: und Afrika\noder Sängerin"
    },
    "name4": {
      "type": "string",
      "description": "name4"
    },
    "umsatzsteuerId": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "DE",
          "length": 9
        }
      },
      "description": "Die Umsatzsteuer-ID des Geschäftspartners. Beispiel: DE 813281825"
    },
    "glaeubigerId": {
      "type": "string",
      "faker": {
        "string.numeric": 6
      },
      "description": "* Die Gläubiger-ID welche im Zahlungsverkehr verwendet wird- Z.B. DE 47116789"
    },
    "emailAdresse": {
      "type": "string",
      "faker": "internet.email",
      "description": "emailAdresse"
    },
    "website": {
      "type": "string",
      "faker": "internet.url",
      "description": "Internetseite des Marktpartners. Beispiel: www.mp-energie.de"
    },
    "gewerbekennzeichnung": {
      "type": "boolean",
      "description": "Kennzeichnung ob es sich um einen Gewerbe/Unternehmen (gewerbeKennzeichnung = true)\noder eine Privatperson handelt. (gewerbeKennzeichnung = false)"
    },
    "hrnummer": {
      "type": "string",
      "faker": {
        "string.numeric": 6
      },
      "description": "Handelsregisternummer des Geschäftspartners"
    },
    "amtsgericht": {
      "type": "string",
      "faker": "location.city",
      "description": "Amtsgericht bzw Handelsregistergericht, das die Handelsregisternummer herausgegeben hat"
    },
    "partneradresse": {
      "$ref": "../com/Adresse.schema.json",
      "description": "Adresse des Geschäftspartners, an der sich der Hauptsitz befindet. Details"
    },
    "externeKundenummerLieferant": {
      "type": "string",
      "faker": {
        "string.numeric": 6
      },
      "description": "externeKundenummerLieferant"
    },
    "externeReferenzen": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../com/ExterneReferenz.schema.json"
      },
      "description": "Hier können IDs anderer Systeme hinterlegt werden (z.B. eine SAP-GP-Nummer) (Details siehe\nExterneReferenz)"
    },
    "geschaeftspartnerrolle": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../enum/Geschaeftspartnerrolle.schema.json"
      },
      "description": "Rolle, die der Geschäftspartner hat (z.B. Interessent, Kunde)."
    },
    "kontaktweg": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../enum/Kontaktart.schema.json"
      },
      "description": "Bevorzugter Kontaktweg des Geschäftspartners."
    },
    "ansprechpartner": {
      "$ref": "../bo/Ansprechpartner.schema.json",
      "description": "Ansprechpartner as in EDIFACT CTA+IC' COM+?+3222271020:TE', that includes e.g. the phone number of customer."
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Geschaeftspartner.json
{
  "boTyp": "GESCHAEFTSPARTNER",
  "versionStruktur": "1",
  "anrede": "Dr.",
  "name1": "Schumacher",
  "name2": "Ilias",
  "name3": "dolor amet aliqua velit veniam",
  "name4": "eiusmod ex",
  "umsatzsteuerId": "DE011100001",
  "glaeubigerId": "162922",
  "emailAdresse": "Tyler.Munch@hotmail.com",
  "website": "https://brandneu-malaria.name/",
  "gewerbekennzeichnung": true,
  "hrnummer": "328848",
  "amtsgericht": "Hamm",
  "partneradresse": {
    "postleitzahl": "36306",
    "ort": "Alt Domenic",
    "strasse": "Freiheitstr.",
    "hausnummer": "88",
    "postfach": "sint aliquip ullamco",
    "adresszusatz": "laborum deserunt magna",
    "coErgaenzung": "amet in ea consequat",
    "landescode": "TL",
    "ortsteil": "Chantalscheid",
    "zusatzInformation": {
      "zusatz1": "exercitation officia aute",
      "zusatz2": "officia ea in occaecat",
      "zusatz3": "Ut laborum sunt commodo fugiat",
      "zusatz4": "cupidatat elit aute esse ad",
      "zusatz5": "est cupidatat proident ipsum"
    }
  },
  "externeKundenummerLieferant": "654678",
  "externeReferenzen": [
    {
      "exRefName": "Kundennummer beim Altlieferanten",
      "exRefWert": "6864910032"
    }
  ],
  "geschaeftspartnerrolle": [
    "ABLESEKARTENEMPFAENGER"
  ],
  "kontaktweg": [
    "TELEFONAT"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Geschaeftspartner.json
{
  "boTyp": "GESCHAEFTSPARTNER",
  "versionStruktur": "1",
  "anrede": "Herr",
  "name1": "Schimmer",
  "name2": "Christiano",
  "name3": "sed",
  "name4": "dolore consectetur mollit et",
  "umsatzsteuerId": "DE000110001",
  "glaeubigerId": "635855",
  "emailAdresse": "Titus.Herschmann@gmail.com",
  "website": "https://stimmig-ebene.info/",
  "gewerbekennzeichnung": true,
  "hrnummer": "366706",
  "amtsgericht": "Castrop-Rauxel",
  "partneradresse": {
    "postleitzahl": "25892",
    "ort": "Hanau",
    "strasse": "Pfeilshofstr.",
    "hausnummer": "23b",
    "postfach": "ex",
    "adresszusatz": "esse id laboris dolor",
    "coErgaenzung": "fugiat nisi cillum deserunt",
    "landescode": "TK",
    "ortsteil": "Süd Gerrit",
    "zusatzInformation": {
      "zusatz1": "dolor ut sint laboris",
      "zusatz2": "anim",
      "zusatz3": "nisi occaecat est incididunt irure",
      "zusatz4": "commodo",
      "zusatz5": "non id dolore est"
    }
  },
  "externeKundenummerLieferant": "025258",
  "externeReferenzen": [
    {
      "exRefName": "Kundennummer beim Lieferanten",
      "exRefWert": "3404972736"
    }
  ],
  "geschaeftspartnerrolle": [
    "INTERESSENT"
  ],
  "kontaktweg": [
    "FAX"
  ],
  "ansprechpartner": {
    "boTyp": "ANSPRECHPARTNER",
    "versionStruktur": "1",
    "nachname": "Carlsohn",
    "eMailAdresse": "Cecilia50@yahoo.com",
    "rufnummern": [
      {
        "nummerntyp": "SAMMELFAX",
        "rufnummer": "+49-5798-58540308"
      }
    ]
  }
}
