=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Leistungskurvendefinition.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Leistungskurvendefinition.schema.json",
  "title": "Leistungskurvendefinition",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "LEISTUNGSKURVENDEFINITION"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "beginndatum": {
      "type": "string",
      "format": "date-time",
      "description": "beginndatum"
    },
    "endedatum": {
      "type": "string",
      "format": "date-time",
      "description": "endedatum"
    },
    "version": {
      "type": "string",
      "format": "date-time",
      "description": "version"
    },
    "code": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "CODE_",
          "length": 4
        }
      },
      "description": "code"
    },
    "notwendigkeit": {
      "$ref": "../enum/DefinitionenNotwendigkeit.schema.json"
    },
    "leistungskurven": {
      "type": ["array", "null"],
      "items": {
        "$ref": "../com/Leistungskurve.schema.json"
      },
      "description": "leistungskurven"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Leistungskurvendefinition.json
{
  "boTyp": "LEISTUNGSKURVENDEFINITION",
  "versionStruktur": "1",
  "beginndatum": "1926-03-02T23:25:04.0Z",
  "endedatum": "1924-02-16T10:52:57.0Z",
  "version": "1936-01-08T21:08:34.0Z",
  "code": "CODE_1111",
  "notwendigkeit": "ZAEHLZEITDEFINITIONEN_WERDEN_NICHT_VERWENDET",
  "leistungskurven": [
    {
      "code": "CODE_0110",
      "aenderungszeitpunkt": "1958-06-19T11:52:55.0Z",
      "haeufigkeit": "JAEHRLICH",
      "uebermittelbarkeit": "NICHT_ELEKTRONISCH",
      "schwellwert": {
        "obererSchwellwert": 10.5,
        "untererSchwellwert": 2.5,
        "konfigurationsprodukt": "KONF_1000"
      },
      "konfigurationsprodukt": "KONF_0111"
    }
  ]
}
