=== conuti-gmbh/bo4e-schema/schemas/v1/bo/Lokationsbuendel.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Lokationsbuendel.schema.json",
  "title": "Lokationsbuendel",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "LOKATIONSBUENDEL"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1"
    },
    "lokationsbuendelstrukturId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      }
    },
    "lokationsbuendelNummer": {
      "type": "integer"
    },
    "standardisierteLokationsbuendelstruktur": {
      "type": "boolean"
    },
    "datenqualitaet": {
      "$ref": "../enum/Datenqualitaet.schema.json"
    },
    "gueltigkeitszeitraum": {
      "$ref": "../com/Zeitraum.schema.json"
    },
    "zuordnungObjectcode": {
      "type": "array",
      "items": {
        "$ref": "../com/ZuordnungObjectcode.schema.json"
      }
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Lokationsbuendel.json
{
  "boTyp": "LOKATIONSBUENDEL",
  "versionStruktur": "1",
  "lokationsbuendelstrukturId": "61280835795",
  "lokationsbuendelNummer": -28443244,
  "standardisierteLokationsbuendelstruktur": false,
  "datenqualitaet": "INFORMATIVE_DATEN",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "MINUTE",
    "dauer": 0,
    "startdatum": "1898-07-15T20:15:13.0Z",
    "enddatum": "1894-10-10T23:49:05.0Z",
    "einheit": "VIERTEL_STUNDE",
    "ableseZeitraum": "155652",
    "abrechnungsZeitraum": "229849",
    "zeitraumText": "Lorem",
    "zeitraumId": 4
  },
  "zuordnungObjectcode": [
    {
      "referenzLokationsTyp": "TRANCHE",
      "referenzLokationsId": "31689506836",
      "vorgelagerteLokationTyp": "TECHNISCHE_RESSOURCE",
      "vorgelagerteLokationId": "97699041667",
      "objectcode": [
        {
          "objectcode": "CODE_000011",
          "lokationsbuendelNummer": 3
        }
      ],
      "referenzMarktlokationTechnischeRessource": [
        "02086643798"
      ]
    }
  ]
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Lokationsbuendel.json
{
  "boTyp": "LOKATIONSBUENDEL",
  "versionStruktur": "1",
  "lokationsbuendelstrukturId": "93715456522",
  "lokationsbuendelNummer": 20248209,
  "standardisierteLokationsbuendelstruktur": false,
  "datenqualitaet": "GUELTIGE_DATEN",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "SEKUNDE",
    "dauer": 2,
    "startdatum": "1954-07-10T14:16:49.0Z",
    "enddatum": "1946-08-29T16:11:04.0Z",
    "einheit": "JAHR",
    "ableseZeitraum": "637015",
    "abrechnungsZeitraum": "935333",
    "zeitraumText": "velit",
    "zeitraumId": 9
  },
  "zuordnungObjectcode": [
    {
      "referenzLokationsTyp": "NELO",
      "referenzLokationsId": "33473227261",
      "vorgelagerteLokationTyp": "NELO",
      "vorgelagerteLokationId": "43215940245",
      "objectcode": [
        {
          "objectcode": "CODE_001100",
          "lokationsbuendelNummer": 1
        }
      ],
      "referenzMarktlokationTechnischeRessource": [
        "08531982527"
      ]
    }
  ]
}
