=== conuti-gmbh/bo4e-schema/schemas/schemas/v1/bo/AdHocSteuerkanal.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/AdHocSteuerkanal.schema.json",
  "title": "AdHocSteuerkanal",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "AD_HOC_STEUERKANAL"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "konfigurationsprodukt": {
      "type": "string",
      "faker": {
        "string.numeric": 14
      },
      "description": "konfigurationsprodukt"
    },
    "zieladresse": {
      "$ref": "../com/Zieladresse.schema.json"
    },
    "aussteller": {
      "$ref": "../com/Aussteller.schema.json"
    },
    "zertifikatsNutzer": {
      "$ref": "../com/ZertifikatsNutzer.schema.json"
    },
    "IPAdresseCLSDevice": {
      "$ref": "../com/IPAdresseCLSDevice.schema.json"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/AdHocSteuerkanal.json
{
  "boTyp": "AD_HOC_STEUERKANAL",
  "versionStruktur": "1",
  "konfigurationsprodukt": "04300570676214",
  "zieladresse": {
    "zieladresse1": "commodo sit mollit reprehenderit",
    "zieladresse2": "qui",
    "zieladresse3": "labore nisi fugiat laboris sed",
    "zieladresse4": "dolor sint nisi quis",
    "zieladresse5": "Lorem quis ut"
  },
  "aussteller": {
    "aussteller1": "ut esse aliquip commodo",
    "aussteller2": "cupidatat aliqua tempor culpa",
    "aussteller3": "dolore velit ea",
    "aussteller4": "ut tempor sed",
    "aussteller5": "in mollit occaecat"
  },
  "zertifikatsNutzer": {
    "zertifikatsNutzer1": "dolor sunt enim eu",
    "zertifikatsNutzer2": "commodo do non",
    "zertifikatsNutzer3": "mollit",
    "zertifikatsNutzer4": "eiusmod pariatur proident",
    "zertifikatsNutzer5": "velit nisi dolor"
  },
  "IPAdresseCLSDevice": {
    "IPAdresseCLSDevice1": "culpa",
    "IPAdresseCLSDevice2": "ipsum pariatur exercitation anim",
    "IPAdresseCLSDevice3": "Ut ad irure aliqua deserunt",
    "IPAdresseCLSDevice4": "pariatur aute",
    "IPAdresseCLSDevice5": "proident sed Ut laboris"
  }
}
