=== conuti-gmbh/bo4e-schema/schemas/schemas/v1/bo/Kommunikationsdaten.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Kommunikationsdaten.schema.json",
  "title": "Kommunikationsdaten",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "KOMMUNIKATIONSDATEN"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "gueltigkeit": {
      "type": "string",
      "format": "date-time",
      "description": "gueltigkeit"
    },
    "kommunikationsDatenBlattInaktiv": {
      "type": "boolean",
      "description": "kommunikationsDatenBlattInaktiv"
    },
    "marktteilnehmer": {
      "$ref": "../bo/Marktteilnehmer.schema.json"
    },
    "kommunikationsangaben": {
      "type": "array",
      "items": {
        "$ref": "../bo/Marktteilnehmer.schema.json"
      },
      "description": "kommunikationsangaben"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Kommunikationsdaten.json
{
  "boTyp": "KOMMUNIKATIONSDATEN",
  "versionStruktur": "1",
  "gueltigkeit": "1908-06-19T07:30:28.0Z",
  "kommunikationsDatenBlattInaktiv": false,
  "marktteilnehmer": {
    "boTyp": "MARKTTEILNEHMER",
    "versionStruktur": "1",
    "geschaeftspartnerrolle": "LIEFERANT",
    "anrede": "Frau",
    "name1": "Östringer",
    "name2": "Steven",
    "name3": "consectetur",
    "name4": "cupidatat eu aliquip",
    "partneradresse": {
      "postleitzahl": "21043",
      "ort": "Unna",
      "strasse": "Leimbacher Hof",
      "hausnummer": "470",
      "postfach": "qui fugiat",
      "adresszusatz": "consectetur et",
      "coErgaenzung": "in cupidatat elit officia",
      "landescode": "VA",
      "ortsteil": "Neu Isabelleburg",
      "zusatzInformation": {
        "zusatz1": "eu",
        "zusatz2": "mollit cupidatat exercitation",
        "zusatz3": "occaecat quis minim laboris",
        "zusatz4": "laborum in pariatur cupidatat",
        "zusatz5": "Lorem officia Duis cillum"
      }
    },
    "gewerbekennzeichnung": false,
    "externeKundenummerLieferant": "tempor officia nisi",
    "marktrolle": "BKO",
    "rollencodenummer": "263861356",
    "rollencodetyp": "GLN",
    "umsatzsteuerId": "DE010100000",
    "steuernummer": "547551489",
    "ansprechpartner": {
      "boTyp": "ANSPRECHPARTNER",
      "versionStruktur": "1",
      "nachname": "Stube",
      "eMailAdresse": "Thalia65@yahoo.com",
      "rufnummern": [
        {
          "nummerntyp": "ABTEILUNGFAX",
          "rufnummer": "+49-2079-54045862"
        }
      ]
    },
    "makoadresse": "sed proident Duis adipisicing aliquip",
    "downloadlinkZertifikat": "https://wohltuend-kino.ch",
    "amtsgericht": "West Nisascheid",
    "hrnummer": "745389",
    "website": "https://majestatisch-insekt.com",
    "faxnummer": "+49-8884-34403574",
    "kommunikationsrolle": "WECHSELPROZESSE",
    "weiterverpflichtet": false,
    "kommunikationsparameter": {
      "zieladresse": {
        "zieladresse1": "tempor non ullamco",
        "zieladresse2": "velit nulla officia",
        "zieladresse3": "laboris sint velit et ipsum",
        "zieladresse4": "laboris aute laborum aliqua enim",
        "zieladresse5": "id in adipisicing sed"
      },
      "zertifikatsAussteller": {
        "zertifikatsAussteller1": "fugiat ipsum esse",
        "zertifikatsAussteller2": "commodo in dolor",
        "zertifikatsAussteller3": "tempor velit fugiat",
        "zertifikatsAussteller4": "veniam amet do",
        "zertifikatsAussteller5": "elit consequat enim"
      },
      "zertifikatsNutzer": {
        "zertifikatsNutzer1": "anim aliquip consectetur esse fugiat",
        "zertifikatsNutzer2": "voluptate deserunt Lorem laboris",
        "zertifikatsNutzer3": "eu nisi esse ad fugiat",
        "zertifikatsNutzer4": "officia nisi",
        "zertifikatsNutzer5": "fugiat aliqua nisi adipisicing"
      }
    },
    "messstellenbetreiberEigenschaft": "WETTBEWERBLICHER_MESSSTELLENBETREIBER",
    "bankverbindung": [
      {
        "verwendungszweck": "BV_ZAHLUNG_NNA",
        "iban": "AL1940790365522X42C362874N7O",
        "kontoinhaber": "Peter Borsch",
        "bic": "GXZCCXCOXXX",
        "kreditinstitut": "Jasinski, Fuhlbrügge und Scholz"
      }
    ],
    "erreichbarkeit": [
      {
        "verfuegbarkeit": "DIENSTAG",
        "zeit": "eu in Ut"
      }
    ],
    "ipAdresse": "6f11:9415:fae0:5c25:6894:660b:7a95:afbf",
    "ipRange": {
      "untereGrenze": "9369:ad0d:0ae3:4deb:8152:6ceb:7c46:b3ba",
      "obereGrenze": "235.170.218.39"
    }
  },
  "kommunikationsangaben": [
    {
      "boTyp": "MARKTTEILNEHMER",
      "versionStruktur": "1",
      "geschaeftspartnerrolle": "INTERESSENT",
      "anrede": "Frau",
      "name1": "Faulhaber",
      "name2": "Alia",
      "name3": "consectetur qui ut proident dolor",
      "name4": "ullamco",
      "partneradresse": {
        "postleitzahl": "61448",
        "ort": "Neumünster",
        "strasse": "Karl-Friedrich-Goerdeler-Str.",
        "hausnummer": "64a",
        "postfach": "velit officia cillum",
        "adresszusatz": "in deserunt dolore dolor",
        "coErgaenzung": "adipisicing",
        "landescode": "SN",
        "ortsteil": "Bad Angeliquescheid",
        "zusatzInformation": {
          "zusatz1": "non do aute",
          "zusatz2": "et mollit pariatur",
          "zusatz3": "mollit Excepteur",
          "zusatz4": "Ut laborum tempor nulla pariatur",
          "zusatz5": "proident"
        }
      },
      "gewerbekennzeichnung": false,
      "externeKundenummerLieferant": "consectetur consequat magna",
      "marktrolle": "KN",
      "rollencodenummer": "425135886",
      "rollencodetyp": "BDEW",
      "umsatzsteuerId": "DE000000010",
      "steuernummer": "741102803",
      "ansprechpartner": {
        "boTyp": "ANSPRECHPARTNER",
        "versionStruktur": "1",
        "nachname": "Lenfers",
        "eMailAdresse": "Xenia.Caspers@gmail.com",
        "rufnummern": [
          {
            "nummerntyp": "SAMMELRUF",
            "rufnummer": "(04104) 9017096"
          }
        ]
      },
      "makoadresse": "fugiat dolor in",
      "downloadlinkZertifikat": "https://exzessiv-kilogramm.name/",
      "amtsgericht": "Bühlerburg",
      "hrnummer": "296305",
      "website": "https://poetisch-sache.net",
      "faxnummer": "+49-021-9975225",
      "kommunikationsrolle": "BILANZIERUNGSPROZESSE",
      "weiterverpflichtet": false,
      "kommunikationsparameter": {
        "zieladresse": {
          "zieladresse1": "nisi dolor",
          "zieladresse2": "voluptate in commodo veniam",
          "zieladresse3": "pariatur in est nostrud Lorem",
          "zieladresse4": "aliqua sint velit cupidatat elit",
          "zieladresse5": "laborum sint"
        },
        "zertifikatsAussteller": {
          "zertifikatsAussteller1": "consectetur pariatur ad labore",
          "zertifikatsAussteller2": "nulla mollit occaecat incididunt pariatur",
          "zertifikatsAussteller3": "deserunt",
          "zertifikatsAussteller4": "ipsum quis in commodo",
          "zertifikatsAussteller5": "anim magna culpa"
        },
        "zertifikatsNutzer": {
          "zertifikatsNutzer1": "et nulla sed",
          "zertifikatsNutzer2": "Ut laborum",
          "zertifikatsNutzer3": "do",
          "zertifikatsNutzer4": "dolore aliqua",
          "zertifikatsNutzer5": "officia Duis qui do occaecat"
        }
      },
      "messstellenbetreiberEigenschaft": "GRUNDZUSTAENDIGER_MESSSTELLENBETREIBER",
      "bankverbindung": [
        {
          "verwendungszweck": "BV_ZAHLUNG_MSB_ABRECHNNUNG",
          "iban": "AZ05ZPHV74030080582360800016",
          "kontoinhaber": "Laureen Oppong",
          "bic": "UAPQVE4ZXXX",
          "kreditinstitut": "Kahlert-Schimmer"
        }
      ],
      "erreichbarkeit": [
        {
          "verfuegbarkeit": "MONTAG",
          "zeit": "reprehenderit cillum"
        }
      ],
      "ipAdresse": "dce6:56f7:e6fc:e581:dc05:ba6e:eefb:2af8",
      "ipRange": {
        "untereGrenze": "207.105.8.181",
        "obereGrenze": "218.54.11.234"
      }
    }
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Kommunikationsdaten.json
{
  "boTyp": "KOMMUNIKATIONSDATEN",
  "versionStruktur": "1",
  "gueltigkeit": "1941-05-05T11:34:31.0Z",
  "kommunikationsDatenBlattInaktiv": false,
  "marktteilnehmer": {
    "boTyp": "MARKTTEILNEHMER",
    "versionStruktur": "1",
    "geschaeftspartnerrolle": "LIEFERANT",
    "anrede": "Frau",
    "name1": "Cronjäger",
    "name2": "Korbinian",
    "name3": "officia commodo Excepteur",
    "name4": "nulla Ut",
    "partneradresse": {
      "postleitzahl": "64802",
      "ort": "West Emelieburg",
      "strasse": "Auf dem Lehn",
      "hausnummer": "33",
      "postfach": "officia",
      "adresszusatz": "irure cupidatat aliquip magna proident",
      "coErgaenzung": "ipsum sed nisi pariatur quis",
      "landescode": "CI",
      "ortsteil": "Emirdorf",
      "zusatzInformation": {
        "zusatz1": "Excepteur",
        "zusatz2": "eu ut consectetur Duis",
        "zusatz3": "est elit in irure",
        "zusatz4": "non laborum aliquip dolor",
        "zusatz5": "dolor exercitation Duis"
      }
    },
    "gewerbekennzeichnung": true,
    "externeKundenummerLieferant": "dolor Excepteur incididunt",
    "marktrolle": "UENB",
    "rollencodenummer": "342654552",
    "rollencodetyp": "BDEW",
    "umsatzsteuerId": "DE011001010",
    "steuernummer": "270419426",
    "ansprechpartner": {
      "boTyp": "ANSPRECHPARTNER",
      "versionStruktur": "1",
      "nachname": "Dingelstedt",
      "eMailAdresse": "Theodor.Rose@gmail.com",
      "rufnummern": [
        {
          "nummerntyp": "ABTEILUNGFAX",
          "rufnummer": "+49-5528-89096402"
        }
      ]
    },
    "makoadresse": "anim est",
    "downloadlinkZertifikat": "https://bahnbrechend-tor.info",
    "amtsgericht": "Velbert",
    "hrnummer": "828536",
    "website": "https://umwerfend-alphabet.org/",
    "faxnummer": "(07398) 0471614",
    "kommunikationsrolle": "WECHSELPROZESSE",
    "weiterverpflichtet": false,
    "kommunikationsparameter": {
      "zieladresse": {
        "zieladresse1": "non Ut quis laboris",
        "zieladresse2": "velit sunt commodo aute sed",
        "zieladresse3": "aute",
        "zieladresse4": "sint laboris",
        "zieladresse5": "amet"
      },
      "zertifikatsAussteller": {
        "zertifikatsAussteller1": "Duis laboris ea ad",
        "zertifikatsAussteller2": "amet in",
        "zertifikatsAussteller3": "proident",
        "zertifikatsAussteller4": "nostrud esse enim",
        "zertifikatsAussteller5": "anim ipsum in"
      },
      "zertifikatsNutzer": {
        "zertifikatsNutzer1": "ut culpa",
        "zertifikatsNutzer2": "consequat laborum",
        "zertifikatsNutzer3": "adipisicing irure mollit quis",
        "zertifikatsNutzer4": "tempor laborum Excepteur",
        "zertifikatsNutzer5": "esse cillum Lorem"
      }
    },
    "messstellenbetreiberEigenschaft": "GRUNDZUSTAENDIGER_MESSSTELLENBETREIBER",
    "bankverbindung": [
      {
        "verwendungszweck": "BV_ZAHLUNG_ENT_SPERREN_ABRECHNUNG",
        "iban": "FR510034058682A1ZJ7Y6B8G687",
        "kontoinhaber": "Frau Veronika Gebhardt",
        "bic": "GQHBAXNJ",
        "kreditinstitut": "Hamann KG"
      }
    ],
    "erreichbarkeit": [
      {
        "verfuegbarkeit": "DONNERSTAG",
        "zeit": "do"
      }
    ],
    "ipAdresse": "72.115.67.84",
    "ipRange": {
      "untereGrenze": "c8ba:bef5:b5d4:ece5:dbcc:62bd:f3c7:f0b0",
      "obereGrenze": "33.226.182.130"
    },
    "zuordnungVon": "1909-04-19T01:05:32.0Z",
    "zuordnungBis": "1892-09-27T21:01:31.0Z",
    "bilanzkreis": "irure reprehenderit nulla veniam adipisicing",
    "verwendungszweckBilanzkreis": "SONSTIGE_ERZEUGENDE_MARKTLOKATION"
  },
  "kommunikationsangaben": [
    {
      "boTyp": "MARKTTEILNEHMER",
      "versionStruktur": "1",
      "geschaeftspartnerrolle": "KUNDE",
      "anrede": "Frau",
      "name1": "Klaus",
      "name2": "Ariane",
      "name3": "reprehenderit Duis culpa",
      "name4": "nulla fugiat",
      "partneradresse": {
        "postleitzahl": "78349",
        "ort": "Ost Stinaburg",
        "strasse": "Lötzener Str.",
        "hausnummer": "1",
        "postfach": "consectetur",
        "adresszusatz": "consectetur laborum aliqua mollit consequat",
        "coErgaenzung": "dolor tempor cillum",
        "landescode": "GI",
        "ortsteil": "Marekstadt",
        "zusatzInformation": {
          "zusatz1": "do pariatur in commodo",
          "zusatz2": "ullamco est",
          "zusatz3": "dolore ad",
          "zusatz4": "pariatur ut ullamco",
          "zusatz5": "aute"
        }
      },
      "gewerbekennzeichnung": false,
      "externeKundenummerLieferant": "est nisi culpa",
      "marktrolle": "MSBA",
      "rollencodenummer": "263117115",
      "rollencodetyp": "GLN",
      "umsatzsteuerId": "DE000001110",
      "steuernummer": "500759685",
      "ansprechpartner": {
        "boTyp": "ANSPRECHPARTNER",
        "versionStruktur": "1",
        "nachname": "Manns",
        "eMailAdresse": "Sanja.Hiebl@yahoo.com",
        "rufnummern": [
          {
            "nummerntyp": "ABTEILUNGRUF",
            "rufnummer": "(0893) 902521065"
          }
        ]
      },
      "makoadresse": "laboris amet",
      "downloadlinkZertifikat": "https://arbeitswutig-comic.net",
      "amtsgericht": "Alt Loreen",
      "hrnummer": "502268",
      "website": "https://heiblutig-proton.de/",
      "faxnummer": "+49-3101-60822448",
      "kommunikationsrolle": "DATENAUSTAUSCH",
      "weiterverpflichtet": true,
      "kommunikationsparameter": {
        "zieladresse": {
          "zieladresse1": "nisi Duis quis consequat et",
          "zieladresse2": "labore ad Excepteur",
          "zieladresse3": "deserunt Duis",
          "zieladresse4": "esse nulla laborum sint dolore",
          "zieladresse5": "id sit"
        },
        "zertifikatsAussteller": {
          "zertifikatsAussteller1": "et ullamco esse eiusmod",
          "zertifikatsAussteller2": "nostrud et nulla dolore eu",
          "zertifikatsAussteller3": "proident incididunt",
          "zertifikatsAussteller4": "ad deserunt",
          "zertifikatsAussteller5": "nostrud Excepteur"
        },
        "zertifikatsNutzer": {
          "zertifikatsNutzer1": "veniam eu Duis",
          "zertifikatsNutzer2": "ullamco enim do",
          "zertifikatsNutzer3": "minim ut",
          "zertifikatsNutzer4": "sit dolor",
          "zertifikatsNutzer5": "aliqua ullamco consequat ex Excepteur"
        }
      },
      "messstellenbetreiberEigenschaft": "GRUNDZUSTAENDIGER_MESSSTELLENBETREIBER",
      "bankverbindung": [
        {
          "verwendungszweck": "BV_ZAHLUNG_ENT_SPERREN_ABRECHNUNG",
          "iban": "CR15300987061470800753",
          "kontoinhaber": "Dr. Colin Schieskow",
          "bic": "IPTKYTIIXXX",
          "kreditinstitut": "Camara, Mikitenko und Christ"
        }
      ],
      "erreichbarkeit": [
        {
          "verfuegbarkeit": "DIENSTAG",
          "zeit": "incididunt et"
        }
      ],
      "ipAdresse": "dbaf:247d:72a2:8acc:dde7:af13:87ed:c666",
      "ipRange": {
        "untereGrenze": "38.202.184.116",
        "obereGrenze": "479d:9d7d:a568:abde:21ac:cabb:bb2d:940c"
      },
      "zuordnungVon": "1929-09-30T23:08:13.0Z",
      "zuordnungBis": "1907-01-07T01:28:50.0Z",
      "bilanzkreis": "sit",
      "verwendungszweckBilanzkreis": "VERBRAUCHENDE_MARKTLOKATION"
    }
  ]
}
