=== conuti-gmbh/bo4e-schema/schemas/schemas/v1/bo/Sperrauftrag.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Sperraufrag.schema.json",
  "title": "Sperrauftrag",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "SPERRAUFTRAG"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "treffpunkt": {
      "$ref": "../com/Adresse.schema.json"
    },
    "sperrauftragsart": {
      "$ref": "../enum/Sperrauftragsart.schema.json",
      "description": "Handelt es sich um einen Auftrag zum SPERREN oder ENTSPERREN?"
    },
    "sperrauftragsstatus": {
      "$ref": "../enum/Auftragsstatus.schema.json",
      "description": "Auftragsstatus"
    },
    "sperrauftragsablehngrund": {
      "$ref": "../enum/Sperrauftragsablehngrund.schema.json",
      "description": "Falls Sperrauftragsstatus = ABGELEHNT"
    },
    "sperrauftragsverhinderungsgrund": {
      "$ref": "../enum/Sperrauftragsverhinderungsgrund.schema.json",
      "description": "Falls Sperrauftragsstatus = GESCHEITERT"
    },
    "zaehlernummer": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "ZAEHLER_",
          "length": 6
        }
      },
      "description": "Die Nummer des zu sperrenden ZÃ¤hlers"
    },
    "istVomGerichtsvollzieherAngeordnet": {
      "type": "boolean",
      "description": "True, falls die Sperrung vom Gerichtsvollzieher angeordnet ist."
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Sperrauftrag.json
{
  "boTyp": "SPERRAUFTRAG",
  "versionStruktur": "1",
  "treffpunkt": {
    "postleitzahl": "10985",
    "ort": "Kaufmannburg",
    "strasse": "Otto-Varnhagen-Str.",
    "hausnummer": "20b",
    "postfach": "quis",
    "adresszusatz": "dolor laboris aliqua tempor",
    "coErgaenzung": "anim dolor veniam velit ut",
    "landescode": "AE",
    "ortsteil": "Bad Marcscheid",
    "zusatzInformation": {
      "zusatz1": "in sed nisi in ut",
      "zusatz2": "laboris id",
      "zusatz3": "anim magna",
      "zusatz4": "elit sit in cupidatat sunt",
      "zusatz5": "cupidatat do"
    }
  },
  "sperrauftragsart": "SPERREN",
  "sperrauftragsstatus": "ENFG_LANDSTROMANLAGEN",
  "sperrauftragsablehngrund": "DUPLIKAT",
  "sperrauftragsverhinderungsgrund": "TECHNISCHER_VERHINDERUNGSGRUND",
  "zaehlernummer": "ZAEHLER_111011",
  "istVomGerichtsvollzieherAngeordnet": true
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Sperrauftrag.json
{
  "boTyp": "SPERRAUFTRAG",
  "versionStruktur": "1",
  "treffpunkt": {
    "postleitzahl": "76019",
    "ort": "Jenniferland",
    "strasse": "Burgweg",
    "hausnummer": "67",
    "postfach": "cillum reprehenderit esse ut ipsum",
    "adresszusatz": "mollit laborum",
    "coErgaenzung": "reprehenderit sit ut quis nisi",
    "landescode": "PL",
    "ortsteil": "Hattingen",
    "zusatzInformation": {
      "zusatz1": "occaecat ut",
      "zusatz2": "velit irure sit sunt",
      "zusatz3": "nulla",
      "zusatz4": "laborum ea velit officia amet",
      "zusatz5": "fugiat et in sed"
    }
  },
  "sperrauftragsart": "SPERREN",
  "sperrauftragsstatus": "UMGESETZT",
  "sperrauftragsablehngrund": "FALSCHE_SPANNUNGSEBENE",
  "sperrauftragsverhinderungsgrund": "TECHNISCHER_VERHINDERUNGSGRUND",
  "zaehlernummer": "ZAEHLER_000100",
  "istVomGerichtsvollzieherAngeordnet": true
}
