=== conuti-gmbh/bo4e-schema/schemas/schemas/v1/bo/Zaehler.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/conuti-gmbh/bo4e-schema/master/schemas/v1/bo/Zaehler.schema.json",
  "title": "Zaehler",
  "type": "object",
  "properties": {
    "boTyp": {
      "$ref": "../enum/BOTyp.schema.json",
      "default": "ZAEHLER"
    },
    "versionStruktur": {
      "type": "string",
      "default": "1",
      "description": "versionStruktur"
    },
    "zaehlernummer": {
      "type": "string",
      "faker": {
        "string.binary": {
          "prefix": "ZAEHLER_",
          "length": 6
        }
      },
      "description": "Nummerierung des Zählers, vergeben durch den Messstellenbetreiber"
    },
    "sparte": {
      "$ref": "../enum/Sparte.schema.json",
      "description": "Strom oder Gas."
    },
    "zaehlerauspraegung": {
      "$ref": "../enum/Zaehlerauspraegung.schema.json",
      "description": "Spezifikation die Richtung des Zählers betreffend."
    },
    "zaehlertyp": {
      "$ref": "../enum/Zaehlertyp.schema.json",
      "description": "Typisierung des Zählers"
    },
    "tarifart": {
      "$ref": "../enum/Tarifart.schema.json",
      "description": "Spezifikation bezüglich unterstützter Tarifarten."
    },
    "zaehlerkonstante": {
      "type": "number",
      "format": "float",
      "faker": {
        "number.float": {
          "multipleOf": 0.5,
          "min": 10,
          "max": 30
        }
      },
      "description": "Zählerkonstante auf dem Zähler."
    },
    "eichungBis": {
      "type": "string",
      "format": "date-time",
      "description": "Bis zu diesem Datum ist der Zähler geeicht."
    },
    "zaehlerhersteller": {
      "$ref": "../bo/Geschaeftspartner.schema.json",
      "description": "Der Hersteller des Zählers. Details Geschaeftspartner"
    },
    "gateway": {
      "type": "string",
      "description": "Angabe eines SMGW, mit dem der Zaehler parametrisiert ist",
      "faker": {
        "string.binary": {
          "prefix": "GATEWAY_",
          "length": 6
        }
      }
    },
    "fernschaltung": {
      "$ref": "../enum/Fernschaltung.schema.json",
      "description": "Fernschaltung"
    },
    "messwerterfassung": {
      "$ref": "../enum/Messwerterfassung.schema.json",
      "description": "Messwerterfassung am Zählpunkt"
    },
    "zaehlertypspezifikation": {
      "$ref": "../enum/ZaehlertypSpezifikation.schema.json",
      "description": "Typisierung des Zählers (spezifikation für EHZ und MME)"
    },
    "befestigungsart": {
      "$ref": "../enum/Befestigungsart.schema.json",
      "description": "Befestigungsart"
    },
    "zaehlergroesse": {
      "$ref": "../enum/Geraetemerkmal.schema.json",
      "description": "Zaehlergroesse"
    },
    "mengenumwertertyp": {
      "$ref": "../enum/Mengenumwertertyp.schema.json"
    },
    "volumenerfassung": {
      "$ref": "../enum/Volumenerfassung.schema.json"
    },
    "serialnummer": {
      "type": "string",
      "faker": {
        "string.numeric": 10
      },
      "description": "serialnummer"
    },
    "geraetemerkmal": {
      "$ref": "../enum/Geraetemerkmal.schema.json",
      "description": "Weitere Merkmale des Geräts, zum Beispiel Mehrtarif, Eintarif etc.. Details Geraetemerkmal"
    },
    "herstellungsdatum": {
      "type": "string",
      "format": "date-time",
      "description": "herstellungsdatum"
    },
    "baujahr": {
      "type": "string",
      "$comment": "DTM+Z03",
      "description": "baujahr"
    },
    "messlokationsId": {
      "type": "string",
      "faker": {
        "string.numeric": 33
      },
      "description": "messlokationsId"
    },
    "marktlokationsId": {
      "type": "string",
      "faker": {
        "string.numeric": 11
      },
      "description": "marktlokationsId"
    },
    "geraete": {
      "type": "array",
      "items": {
        "$ref": "../com/Geraet.schema.json"
      },
      "description": "Liste der Geräte, die zu diesem Zähler gehören."
    },
    "zaehlwerke": {
      "type": "array",
      "items": {
        "$ref": "../com/Zaehlwerk.schema.json"
      },
      "description": "Die Zählwerke des Zählers."
    },
    "datenqualitaet": {
      "$ref": "../enum/Datenqualitaet.schema.json"
    },
    "gueltigkeitszeitraum": {
      "$ref": "../com/Zeitraum.schema.json"
    }
  },
  "required": [
    "boTyp",
    "versionStruktur"
  ]
}

=== conuti-gmbh/bo4e-schema/docs/examples/bo/Zaehler.json
{
  "boTyp": "ZAEHLER",
  "versionStruktur": "1",
  "zaehlernummer": "ZAEHLER_100110",
  "sparte": "STROM",
  "zaehlerauspraegung": "ZWEIRICHTUNGSZAEHLER",
  "zaehlertyp": "DREHKOLBENZAEHLER",
  "tarifart": "LEISTUNGSGEMESSEN",
  "zaehlerkonstante": 11.5,
  "eichungBis": "8117",
  "zaehlerhersteller": {
    "boTyp": "GESCHAEFTSPARTNER",
    "versionStruktur": "1",
    "anrede": "Herr",
    "name1": "Bühler",
    "name2": "Stephan",
    "name3": "amet enim veniam",
    "name4": "occaecat dolor ut",
    "umsatzsteuerId": "DE100110111",
    "glaeubigerId": "269580",
    "emailAdresse": "Samia_Gross@hotmail.com",
    "website": "https://gewissenhaft-aids.de",
    "gewerbekennzeichnung": true,
    "hrnummer": "636332",
    "amtsgericht": "Süd Colleenscheid",
    "partneradresse": {
      "postleitzahl": "30821",
      "ort": "Düsseldorf",
      "strasse": "Gutenbergstr.",
      "hausnummer": "72c",
      "postfach": "fugiat incididunt laboris dolore ut",
      "adresszusatz": "reprehenderit",
      "coErgaenzung": "velit Ut ullamco qui irure",
      "landescode": "AN",
      "ortsteil": "West Laurens",
      "zusatzInformation": {
        "zusatz1": "veniam eu officia velit",
        "zusatz2": "dolore",
        "zusatz3": "dolore eu sint nulla nostrud",
        "zusatz4": "veniam sint dolor qui Lorem",
        "zusatz5": "anim quis sed incididunt ex"
      }
    },
    "externeKundenummerLieferant": "222627",
    "externeReferenzen": [
      {
        "exRefName": "Kundennummer beim Altlieferanten",
        "exRefWert": "0956507404"
      }
    ],
    "geschaeftspartnerrolle": [
      "INTERESSENT"
    ],
    "kontaktweg": [
      "E_MAIL"
    ],
    "ansprechpartner": {
      "boTyp": "ANSPRECHPARTNER",
      "versionStruktur": "1",
      "nachname": "Astafei",
      "eMailAdresse": "Damien0@gmail.com",
      "rufnummern": [
        {
          "nummerntyp": "FAX_ZENTRALE",
          "rufnummer": "(0457) 414298616"
        }
      ]
    }
  },
  "gateway": "GATEWAY_010010",
  "fernschaltung": "NICHT_VORHANDEN",
  "messwerterfassung": "FERNAUSLESBAR",
  "zaehlertypspezifikation": "MME_STANDARD",
  "befestigungsart": "STECKTECHNIK",
  "zaehlergroesse": "WASSER_VWZ07",
  "mengenumwertertyp": "TEMPERATURMENGENUMWERTER",
  "volumenerfassung": "SCHLEICHMENGENUNTERDRUECKUNG",
  "serialnummer": "4366002149",
  "geraetemerkmal": "MODEM_GSM",
  "herstellungsdatum": "7386",
  "baujahr": "5416",
  "messlokationsId": "704234359972744304662671585407586",
  "marktlokationsId": "63841449069",
  "geraete": [
    {
      "geraetetyp": "KOMBIMESSWANDLER_IMS_MME",
      "bezeichnung": "commodo",
      "geraetenummer": "78722",
      "geraetereferenz": "REF_110111",
      "geraeteeigenschaften": {
        "geraetetyp": "ZUSTANDSMENGENUMWERTER",
        "geraetemerkmal": "TEMPERATURMENGENUMWERTER",
        "volumenerfassung": "SCHLEICHMENGENUNTERDRUECKUNG",
        "serialnummer": "2603167406",
        "herstellungsdatum": "5702",
        "baujahr": "6022",
        "eichungBis": "0323",
        "faktor": 6.25,
        "firmwareVersion": "FW_0010",
        "herstellerTypbezeichnung": "TYP_011000",
        "simKartenNummer": "70482814611773398536",
        "modemKennungIMSI": "966243493818549",
        "tkProvider": "TK_1111",
        "ipVersion": "4"
      },
      "volumenerfassung": "KENNLINIENKORREKTUR",
      "weitereGeraetenummern": [
        "47742"
      ]
    }
  ],
  "zaehlwerke": [
    {
      "zaehlwerkId": "967837807",
      "bezeichnung": "voluptate velit",
      "richtung": "EINSP",
      "obisKennzahl": "ut",
      "wandlerfaktor": 2,
      "einheit": "PROZENT",
      "schwachlastfaehig": "SCHWACHLASTFAEHIG",
      "verbrauchsart": [
        "SW"
      ],
      "unterbrechbarkeit": "UV",
      "waermenutzung": "WAERMEPUMPE_WAERME",
      "konzessionsabgabe": {
        "satz": "KAS",
        "kosten": 71803084.4137899,
        "kategorie": "voluptate irure"
      },
      "steuerbefreit": false,
      "vorkommastelle": 1,
      "nachkommastelle": 3,
      "abrechnungsrelevant": true,
      "anzahlAblesungen": 2,
      "zaehlzeiten": {
        "register": "in elit mollit pariatur id",
        "zaehlzeitDefinition": "do ipsum dolor et",
        "schwachlastfaehig": "NICHT_SCHWACHLASTFAEHIG"
      },
      "konfiguration": "laboris Duis officia sint reprehenderit",
      "messprodukt": "consectetur laboris elit dolor",
      "wertegranularitaet": "QUARTALSWEISE",
      "notwendigkeitZweiteMessung": "NICHT_VORHANDEN",
      "werteuebermittlungVerwendungszweck": "VORHANDEN",
      "artEMobilitaet": "WB",
      "konfigurationsprodukt": "nulla tempor reprehenderit",
      "keinKonfigurationsprodukt": true,
      "leistungskurvendefinition": "do occaecat ut dolore",
      "verwendungszwecke": [
        {
          "marktrolle": "NB",
          "zweck": [
            "MEHRMINDERMENGENABRECHNUNG"
          ]
        }
      ],
      "verwendungszweckNB": "minim Duis",
      "verwendungszweckLF": "adipisicing id consequat",
      "verwendungszweckUENB": "exercitation in nulla in deserunt",
      "keinProdukt": true
    }
  ],
  "datenqualitaet": "DIFFERENZ_DATEN",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "HALBJAHR",
    "dauer": 0,
    "startdatum": "1898-08-11T06:57:13.0Z",
    "enddatum": "1893-08-31T01:53:46.0Z",
    "einheit": "JAHR",
    "ableseZeitraum": "947858",
    "abrechnungsZeitraum": "911128",
    "zeitraumText": "amet",
    "zeitraumId": 9
  }
}

=== conuti-gmbh/bo4e-schema/docs/docs/examples/bo/Zaehler.json
{
  "boTyp": "ZAEHLER",
  "versionStruktur": "1",
  "zaehlernummer": "ZAEHLER_111001",
  "sparte": "WASSER",
  "zaehlerauspraegung": "ZWEIRICHTUNGSZAEHLER",
  "zaehlertyp": "ULTRASCHALLGASZAEHLER",
  "tarifart": "EINTARIF",
  "zaehlerkonstante": 26.5,
  "eichungBis": "1910-11-29T19:07:48.0Z",
  "zaehlerhersteller": {
    "boTyp": "GESCHAEFTSPARTNER",
    "versionStruktur": "1",
    "anrede": "Prof. Dr.",
    "name1": "Wiechmann",
    "name2": "Nila",
    "name3": "nostrud esse anim consectetur",
    "name4": "sit",
    "umsatzsteuerId": "DE100001101",
    "glaeubigerId": "471195",
    "emailAdresse": "Benno34@hotmail.com",
    "website": "https://cool-daumen.org",
    "gewerbekennzeichnung": true,
    "hrnummer": "783454",
    "amtsgericht": "Bad Alessialand",
    "partneradresse": {
      "postleitzahl": "41410",
      "ort": "Neu Luise",
      "strasse": "Reuschenberger Str.",
      "hausnummer": "14",
      "postfach": "Duis et ullamco",
      "adresszusatz": "amet incididunt",
      "coErgaenzung": "non esse mollit dolore",
      "landescode": "PW",
      "ortsteil": "Bad Mikailland",
      "zusatzInformation": {
        "zusatz1": "esse elit aute id",
        "zusatz2": "esse labore aliqua consequat",
        "zusatz3": "adipisicing",
        "zusatz4": "tempor voluptate sit pariatur eu",
        "zusatz5": "laborum aliqua"
      }
    },
    "externeKundenummerLieferant": "678399",
    "externeReferenzen": [
      {
        "exRefName": "Kundennummer beim Altlieferanten",
        "exRefWert": "4420749928"
      }
    ],
    "geschaeftspartnerrolle": [
      "LIEFERANT"
    ],
    "kontaktweg": [
      "E_MAIL"
    ]
  },
  "gateway": "GATEWAY_100001",
  "fernschaltung": "VORHANDEN",
  "messwerterfassung": "FERNAUSLESBAR",
  "zaehlertypspezifikation": "MME_MEDA",
  "befestigungsart": "DREIPUNKT",
  "zaehlergroesse": "MODEM_GSM_O_LG",
  "mengenumwertertyp": "DICHTEMENGENUMWERTER",
  "volumenerfassung": "HOCHFREQUENZSONDE",
  "serialnummer": "6731227761",
  "geraetemerkmal": "WASSER_WZ03",
  "herstellungsdatum": "1947-07-01T15:15:55.0Z",
  "baujahr": "dolore occaecat",
  "messlokationsId": "297319823173905782929102230489500",
  "marktlokationsId": "18669824974",
  "geraete": [
    {
      "geraetetyp": "OPTIONALE_ZUS_ZAEHLEINRICHTUNG",
      "bezeichnung": "ex labore",
      "geraetenummer": "03395",
      "geraetereferenz": "REF_101110",
      "geraeteeigenschaften": {
        "geraetetyp": "KOMBIMESSWANDLER_IMS_MME",
        "geraetemerkmal": "GAS_G650",
        "faktor": 1.5
      },
      "volumenerfassung": "KENNLINIENKORREKTUR",
      "weitereGeraetenummern": [
        "17927"
      ]
    }
  ],
  "zaehlwerke": [
    {
      "zaehlwerkId": "922904359",
      "bezeichnung": "enim aute ea",
      "richtung": "AUSSP",
      "obisKennzahl": "et",
      "wandlerfaktor": 1,
      "einheit": "KWHK",
      "schwachlastfaehig": "NICHT_SCHWACHLASTFAEHIG",
      "verbrauchsart": "SW",
      "unterbrechbarkeit": "UV",
      "waermenutzung": "WAERMEPUMPE_KAELTE",
      "konzessionsabgabe": {
        "satz": "KAS",
        "kosten": -95596172.61968611,
        "kategorie": "Ut aute est reprehenderit"
      },
      "steuerbefreit": false,
      "vorkommastelle": 5,
      "nachkommastelle": 8,
      "abrechnungsrelevant": true,
      "anzahlAblesungen": 5,
      "zaehlzeiten": {
        "register": "pariatur non officia",
        "zaehlzeitDefinition": "dolor do laborum mollit",
        "schwachlastfaehig": "SCHWACHLASTFAEHIG"
      },
      "konfiguration": "aute cupidatat nulla Excepteur eu",
      "messprodukt": "velit cillum consequat dolor in",
      "wertegranularitaet": "JAEHRLICH",
      "notwendigkeitZweiteMessung": "VORHANDEN",
      "werteuebermittlungVerwendungszweck": "VORHANDEN",
      "artEMobilitaet": "WB",
      "konfigurationsprodukt": "ullamco in",
      "keinKonfigurationsprodukt": false,
      "leistungskurvendefinition": "elit sint dolor",
      "verwendungszwecke": [
        {
          "marktrolle": "DL",
          "zweck": [
            "NETZNUTZUNGSABRECHNUNG"
          ]
        }
      ]
    }
  ],
  "datenqualitaet": "KEINE_DATEN_ERWARTET",
  "gueltigkeitszeitraum": {
    "zeiteinheit": "VIERTEL_STUNDE",
    "dauer": 2,
    "startdatum": "1959-04-08T05:57:32.0Z",
    "enddatum": "1890-09-27T10:56:46.0Z",
    "einheit": "JAHR",
    "ableseZeitraum": "964360",
    "abrechnungsZeitraum": "454763",
    "zeitraumText": "laboris aliqua aliquip ea anim",
    "zeitraumId": 9
  }
}
